[package]
name = "terminus-store"
version = "0.14.1"
authors = ["Matthijs van Otterdijk <matthijs@datachemist.com>"]
edition = "2018"
license = "GPL-3.0-only"
description = "a triple store library"
homepage = "https://terminusdb.com"
repository = "https://github.com/terminusdb/terminus-store/"
documentation = "https://docs.rs/terminus-store/"

[dependencies]
byteorder = "1.4"
futures = "0.3"
futures-locks = "0.6"
tokio = {version = "1.0", features = ["full"]}
tokio-util = {version = "0.6", features = ["codec"]}
bytes = "1.0"
rand = "0.7"
lazy_static = "1.4"
fs2 = "0.4.3"
tar = "0.4"
flate2 = "1.0"
rayon = "1.4"
thiserror = "1.0"
sha-1 = "0.9.2"
hex = "0.4.2"

[dev-dependencies]
tempfile = "3.1"
